### ISSUE TITLE
Support bilingual language 

### ISSUE THREAD

**Issue by sachsongngu** [CueSync/cuesync.github.io#1]
### Prerequisites

- [X] I have [searched](https://github.com/cuesync/cuesync.github.io/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/cuesync/cuesync.github.io/blob/main/.github/CONTRIBUTING.md)

### Proposal

First thing I would like to say your project is great 
It will be more helpful if you add support for two or more vtt file per media, 
Im not a coder, so I can't held, but I know it possible. Please take a look at 
https://toomva.com/video/du-an-adam=18123
And 
studyphim.vn

### Motivation and context

It will create an education platform for language learners

**Comment by nkdas91** [comment]
## 🚀 Update: Multilingual Transcript Support is Here!

Hi, Just a quick update:

CueSync v2.0.0-alpha3 now supports multilingual transcripts! 🎉
You can check out a working example here:
🔗 https://cuesync.github.io/2.0/examples/#multilingual-transcripts

That’s not all — CueSync has been completely restructured as a modern Web Component, making it easier to integrate across all major frameworks like React, Vue, Angular, and more.

This version introduces:

✨ Built-in support for language switching
⚙️ A settings UI for layout, theme, timestamps, and scroll behavior
📦 Proper npm distribution with ESM + UMD builds
💡 Improved styling via CSS custom properties
🧪 This is a prerelease (alpha) version — feel free to try it out and share any feedback.

Thanks again for the feature request and for helping make CueSync better! 🙌
